# Generated by Django 4.0.3 on 2022-03-19 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userextend',
            options={'ordering': ['id'], 'verbose_name': '用户扩展', 'verbose_name_plural': '用户扩展'},
        ),
        migrations.RenameField(
            model_name='major',
            old_name='majoy',
            new_name='major',
        ),
        migrations.AlterField(
            model_name='school',
            name='graSchool',
            field=models.IntegerField(verbose_name='研究生院'),
        ),
        migrations.AlterField(
            model_name='school',
            name='indLine',
            field=models.IntegerField(verbose_name='自主划线'),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='iconImage',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/%Y/%m/%d', verbose_name='头像'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matName', models.CharField(max_length=255, verbose_name='资料名称')),
                ('file', models.FileField(upload_to='materials/%Y/%m/%d/')),
                ('uploadTime', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('downloadLink', models.TextField(verbose_name='下载链接')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='my_api.school', verbose_name='所属学校')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '资料表',
                'verbose_name_plural': '资料表',
                'ordering': ['id'],
            },
        ),
    ]
