# Generated by Django 4.0.3 on 2022-03-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_alter_userextend_options_rename_majoy_major_major_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextend',
            old_name='iconImage',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='material',
            name='downloadLink',
        ),
    ]
